### PR TITLE
Skip passed results for both report table and fetching logs

### LINKED ISSUE #42: report command: download logs of failed tests only
**Is your feature request related to a problem? Please describe.**
Right now I can download convert2rhel log files from all tests that have run for a give Testing Farm job. It's a lot of data to download and it takes time. I'm interesting in logs of only the failed tests though.

**Describe the solution you'd like**
Add filtering to the report download feature.

### PR DESCRIPTION
**Pull request by pholica**
Resolves #42

### CODE REVIEW

**Comment by danmyway** [comment]
Works as intended, thanks @pholica!
```
❯ tesar report --short -l2 -c http://artifacts.osci.redhat.com/testing-farm/9d129ea9-e633-44e6-a6fd-bc84a9ac447c/ --download-logs --skip-pass
Reporting for the requested tasks:
CentOS-8-latest tier0/non-destructive https://api.dev.testing-farm.io/v0.1/requests/9d129ea9-e633-44e6-a6fd-bc84a9ac447c COMPLETE
  > Downloading the log files.
    > Logfiles stored in /var/tmp/tesar/logs/9d129ea9-e633-44e6-a6fd-bc84a9ac447c_logs
+--------------------------------------+-----------------+-----------------+-------------------------------------+--------+
| UUID                                 | Target          | Test Plan       | Test Case                           | Result |
+--------------------------------------+-----------------+-----------------+-------------------------------------+--------+
| 9d129ea9-e633-44e6-a6fd-bc84a9ac447c | CentOS-8-latest |                 |                                     |        |
|                                      |                 | non-destructive |                                     | FAILED |
|                                      |                 |                 | backup_os_release_no_envar          | FAILED |
|                                      |                 |                 | backup_os_release_with_envar        | FAILED |
|                                      |                 |                 | unsuccessful_satellite_registration | FAILED |
|                                      |                 |                 | empty_username_and_password         | FAILED |
+--------------------------------------+-----------------+-----------------+-------------------------------------+--------+

❯ tree /var/tmp/tesar/logs/9d129ea9-e633-44e6-a6fd-bc84a9ac447c_logs/
9d129ea9-e633-44e6-a6fd-bc84a9ac447c_logs/
└── non-destructive
    ├── CentOS-8-latest_backup_os_release_no_envar.log
    ├── CentOS-8-latest_backup_os_release_with_envar.log
    ├── CentOS-8-latest_empty_username_and_password.log
    └── CentOS-8-latest_unsuccessful_satellite_registration.log
```

**Review by danmyway — CHANGES_REQUESTED** [review]
Looks good from my point of view, thanks!
Please just append the CHANGELOG, README and add code comments, we don't need to bulk up my technical debt, thank you!
Also the debug messages would be nice as well :)

**Comment by pholica** [comment]
Thank you for the review. I'm going to fix as much as it's reasonable before I leave for one week. It's possible that not all of the items will be addressed this (and effectively next week).

**Comment by pholica** [comment]
Hmmm, the readme update touches also other options as I merely ran the `tesar report -h` and copied the output so it seems the readme was not updated in one of the previous commits which introduced the change.

**Comment by pholica** [comment]
@danmyway Please review, I believe it should be now eligible for merge.

**Review by danmyway — APPROVED** [review]
Looks good and the changes are super helpful!
Thanks, @pholica

**Pull request merged**
