### PR TITLE
Introduce comparison between 2 test runs mode

### LINKED ISSUE #56: Parse results.xml instead of xunit
A result.xml page might serve as a primary source of truth for generating the report, use xunit only as backup.

### PR DESCRIPTION
**Pull request by fernflower**
To become a real deal some new command line arguments still have to be introduced.
Currently 2 modes are possible (switch is controlled by --level2 argument) - show plans-list comparison or detailed tests-list comparison.

Resolves https://github.com/danmyway/tesar/issues/56

### CODE REVIEW

**Comment by fernflower** [comment]
@danmyway what do you think about it? As I am not the only person on out team to use it for test comparison, is there any chance we can make this test runs comparison functionality an official part of tesar?

**Comment by fernflower** [comment]
Will attach a picture of sample output
`tesar report -c 8f4e2e3e-beb4-4d3a-9b0a-68a2f428dd1b -c c3726a72-8e6b-4c51-88d8-612556df7ac1 --short  --compare --unify-results=tier2=tier2_7to8`
image

**Comment by fernflower** [comment]
Rebased. This PR also contains an amazing fix by mmacura for showing results of runs that ended up in error https://github.com/danmyway/tesar/pull/55

**Comment by fernflower** [comment]
@danmyway Please review

**Comment by fernflower** [comment]
Squashed commits and natively included mmacura's fix https://github.com/danmyway/tesar/pull/55 , so once you merge this - you can close his PR with his code getting in with proper ownership (two for the effort of one deal!).

**Comment by danmyway** [comment]
Great addition, thanks @fernflower.
Please just add docstrings to the new functions, so the technical debt doesn't get too much bigger.
Doesn't need to be a full-fledged docstring, just explaining what it does briefly.
Also the [CHANGELOG](https://github.com/danmyway/tesar/blob/devel/CHANGELOG.md) and [README](https://github.com/danmyway/tesar/blob/devel/README.md) would deserve to have this included.
Thank you!

**Comment by fernflower** [comment]
@danmyway all done, could you please re-review?

**Review by danmyway — APPROVED** [review]
Looks great, thank you @fernflower!
Merging

**Pull request merged**
